"""create releases and release tracks

Revision ID: adaa068838a6
Revises: 3e9fb1b97bc0
Create Date: 2026-09-04 18:14:41.251362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adaa068838a6'
down_revision: Union[str, Sequence[str], None] = '3e9fb1b97bc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('releases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('artist_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('release_type', sa.Text(), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.Column('cover_url', sa.Text(), nullable=True),
    sa.Column('upc', sa.Text(), nullable=True),
    sa.Column('spotify_url', sa.Text(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('release_tracks',
    sa.Column('release_id', sa.UUID(), nullable=False),
    sa.Column('track_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('isrc', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('release_id', 'track_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('release_tracks')
    op.drop_table('releases')
    # ### end Alembic commands ###
