"""add artist relation to users

Revision ID: c3693c37a0f3
Revises: 9dc5e2cf24c0
Create Date: 2026-09-08 15:54:40.757174

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c3693c37a0f3'
down_revision: str | Sequence[str] | None = '9dc5e2cf24c0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('artist_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'artists', ['artist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'artist_id')
    # ### end Alembic commands ###
